language: csharp
os:
  - linux
dist: trusty
dotnet: 2.1.402
mono: none
sudo: required

services:
  - docker

install:
  # build container image
  - docker build -t cityofzion/neo-sharp:latest ./containers/

script:
  # run tests
  - dotnet restore
  - find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_success:
  # if tests ok publish CodeDev report
  - bash <(curl -s https://codecov.io/bash) -v
