language: csharp
os:
  - linux
dist: trusty
dotnet: 2.1.300
mono: none
sudo: required
services:
  - docker
before_install:
  - docker build -t cybertuga/neo-sharp:latest ./containers/
script:
  - dotnet restore
  - find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  - bash <(curl -s https://codecov.io/bash) -v
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=cybertuga/neo-sharp
  - docker push $REPO
env:
  global:
    - secure: I02eSIkQgCOCdCz5q7cprLtzKmAnXTrMiUMD4P9VVsc5UGW14owv4jAIdVRLaTG/4TCr5My4pkNrmNc12I/IpXkE3nPByx0pAIVqIRBTDxWOA8AWHbovJHYHw2PyKbPthZEH+N9Has3YyS49VMmUrhOXZqC+iGQ/plzoIZZZ3RQds0QuAfag3N2rjDHaJPqXGu1O7KnEyAkESTH0cDETc5/ygHRe5vKnyQOg/9zK4lQoWU4QHzh58HNDzL2t99Jtx5vLomUJ/MCL5hKlPNAIEmv+TQsFR58DcXkuhOgCW6xEMywdgY65ItMR9YpHvnJy2q/qrH1RQTFaSjdVwgFwcqBiQFsX9jr+FOwf+Ss/Y+jCiV2BFg/+Nze4cL10wercTifockHPaSzw/y/Z2YgwJZa9yEQygM1FCW/ExNBM17zSNCkvEto14UzgpFAsDiOpuNUBwwDFBEh9awpwTY/AixYLeGTctoM0qGco9i2+tv+gap5vaHyLBLRjmQrBT99LSxxJJzDf/hKU2RgIHM70AotI8jPWHf/NxRHW09I88ZJGQPPDYW47/WHQlXDaIfZeNBE94tcJOMCzWnjHT6f+WYVoicXDXtXBwKzgpKNaNff0TWaYK//PJjIlE+NsfsFITiE2sPq3kHMcGj/SHlkk9wNCdSslqlw1YK45utIu47E=
    - secure: Dq30BdPPzmAVMGxfEt3HZRaa6mR5Qgr1+AN3CGoGqzeDYYOny/N88tmrbQ3u0udCNNyX72jQo3D0ANC9TnImA++Do3Yz9UOHbmze227TQ4D964VT70mmV3SvtBt3SpTYE+MqiciJMssgGrmV8gvyzEvZvvChYz9vO7PpmrSJcUDLnqmOF/kb8ARTzZYsQy8oj/YyVZIbfp1GqSAowzrzuwj4FSIOoNwDPj/Fi0T6pNtHFofMuXej2NttG2FtdbfKR3qjVIpUBmlDII7p9hn1efA0vg1x9z+niDPLpZLUj37Zoo8XDIYH3SlnRUPp4OBJxgMjUGnFlEHvPzlrNRCgGKcy5r47q+7rKjP/lS11/mRZN0laprWK5Ku498VT+dMFU4FhHfL/SC29JnkRTOKx2NPOXCi3jyjQfzPTNn8AK470+wOQJnbPnsRfg+Elxin+LFdiqtKvsHcvsebOC+YxWQsu6aOfBOegmIq0bx/Y5abEfC8ECx6qzOku1ckoQN4UuJiEbgcxfAmWLGaeedW74MQdpfv8GyvS6YRkkN2P6AXHzGUdWwt1ILKylx7Pw2coBcomHfmbFiV3Fm1VUoxJ8puD3cyMfO+RbYO/ufzAbh/TbicvGZYuZOxRcKaNZFrABOb129bMpffVKC2YBG+qC3cbjeWMhGM6agXMEky4Cg0=
    - secure: HFHPw1KxXStaUkdCH0XMMVfyua1tbtWfdOt1hhBNJ5EzopjXw9Cao7k9DROFMxklH9UMtKPJiRVCtKiI/t6Ib1KZAygmMuTQp9UfbP3IoGTje9WV4J6xBL8Q+Y3B3LWEv08XtXzeHJP5SXONygawp8suTdcBG+VaoIAvtXFq9xxJw+xAWRRZ2H3t5STmWNdR/5SVamfDUo1WWwZ/J23wxNtcjIFHvJDcunl0QYdtv/qC/tDwcDvlhu5888hXZ6XWIw3khMlHAXJEaamqgC/xhj2TFHi7EVL4pF8gZ2Le4i7vGeiPfJqs+zVBGaJDxA52d+3NypS/gOBsjM8GZslgBvI3/sfwdXAYRkyjjo132mzDFwX3UdKLeYjqEtc0ke/quMp2yFZC7SV4RsRm6hhXLVY0ZhDInyiqvJB3rksEBjAcX5CReVXiRiSAK1TL2pVsKyGnmwujmYEO+RtLS+YVRafo0AWLBr++3wjysyV151WZauvt/oI1GGC3ZFRNJHqZIM6mDEp5jU1+6CTRPYjpmRa4RH1eTsbj4w3O2fDhVNZMfJ+mrSrdpTHTEzgTt8V0IVic0adFYAsYbf7LSsTIuQqO5Z4MD6WSTR5lE+h0nisHpDijG/3EOwlZUMYtmN/4BCQwSlSM7u0IonAu4iQsSGXqjs+R200OyO5kM1vF4fU=
