language: csharp
os:
  - linux
dist: trusty
dotnet: 2.1.402
mono: none
sudo: required

env:
  global:
    DOCKER_USER:
      secure: Jdo2yXp5kHgnWbEHgt8rkqMUX1BsO0ffijlKj1Sn4NK9guJavddI+1O7AJIzovl/f1oTPKQxEu9IcP8UGpuyscOjJt8dnGF5sTLhvJ+3Xb9lugBQsOB0er6oFOb5dbXlB/9awXKpkLdHbdcOvmjZ4m5U5rOtXAbrPimFw1zKJFCLx81rPKXmK8AaZj7EF3ntv3IzqevxrppUeIz6cQJwxNQrlBJVlwGrRKLX5qMwrft7Piu9BN/7D+hqt9B0+pH9eEk+ecUkZ1T3Ff2jAygl0eBloGtDGf+YJ3OGIYLf9Xmci05p0bqimW9gUiZ7w/7Wjj/SNOQ5TFMfBIZScj3tgo03vYt622kIQgdYY7OEDHrxjUg/axkPaWpTfXxvGA94ey9F/sT74kFHGOMJh4wFy3atHFzI3U79HtHnY19jxk/WoX0xF52UZHZ90tQt2RQvmFddYnf53f4mV27MnJhogU9s2TKyjobCZcPvw8ZGIvRgM0vCAOfHIQf8PmhKO5dufr7H0BAIgsRvhlapRRB+mh3+cI4Yd6EjGmWXkOpL0sXaLkHg7ONm0l+0e6A1fkcy1HFApZm1iEbEln+arGABgSw0i2kugFKOhg3dUYm/H7gywYb/ofj4C+K2KFmfUlY0Y8N6HJjwbqN6h3DWR+DHK5Nc5sAk/zMJutuMh2UajWc=
    DOCKER_PASS:
      secure: dq54Ms4hN0nWlmes9qb2MtXRtBYfPsEFBScxpSSxxmqGqabIHLUl5qmOTG59tfcgYntF9ZgoLqi9ap0blFaJPvJd+GaDlyOkcjtwEMHdZHbbNNkxpsollt8QOUvckW+rBXNNwuXziEjkls43bc9F0NWVqzyrB1fShbycjRD5J893lRE4PMpHO+eF1OmrtMLf0ZavEQePvpvoTCgEG2Wj5E9mKK0HJXpVn2qaO1LOHuuo0nYIIKrF2jlf8GKsxQyFUGC5moCsYBvnVtIWRVqdGkaiFVLhsx/e8kGG0YZc2k1IQluCVrkJ/UdutpV6WAzvaXN/bJwga5FwF8GoLPicMAiC0ullPw4D9tbZ/1ksCNHOjNALeQVxfC2AaOctlRmJWLmsW/KUvIQlxjfF462ZMk4+BNzH+YgkSDHL1VZmJqrjQj3E0Fte7pveRyjI+q6MXyWhoEhs/ucyZyimOeCXxOeR2DRg5EFfBQntc6h0VvrDc4uBrGwGrIfNHfs/96FYyNGUFpTx7BHeE4PGFBl1yBUzGciLgoZESXutK7FuWQurle/9sotYZUrsrm9cyAU+AhihdFtq3QniBrX7GLoVqDIb+oSbeE56WcMX1A3/bbC/vkKBVBCRokoQB50LtbvyH2S5MfKEID6oTCpCGdQEuFE0fE28tpAq5XlxKj22Xn8=

services:
  - docker

install:
  # Build both docker images (sdk and runtime)
  - docker build --target builder -t neo-sharp_sdk ./containers/
  - docker build --target runtime -t neo-sharp_runtime ./containers/

script:
  - dotnet restore
  - find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_success:
  # After all tests OK, Send CodeDov report
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - bash <(curl -s https://codecov.io/bash) -v

before_deploy:
  # To deploy the docker images, first do login and tag
  - bash -c "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag neo-sharp_sdk cityofzion/neo-sharp:sdk_$TAG
  - docker tag neo-sharp_runtime cityofzion/neo-sharp:$TAG

deploy:
  # Push images to official docker repository
  - provider: script
    script: bash -c "docker push cityofzion/neo-sharp"
    on:
      repo: CityOfZion/neo-sharp
