language: csharp
os:
  - linux
dist: trusty
dotnet: 2.1.300
mono: none
sudo: required

env:
  global:
    - secure: HYye9FxO66bBgpwphNYRY38y9ZS5tu3VCOyTTL9+bI18Zm5X52lSDAxRKbpg2MlF2twVxt/N1U/ckCM9/CVKr8SVdQ1kHiNLr/H0Mj53OFPyLmxDUxffsYNWqKtVAU1oCj1hl/f+Q8MWZ1P+z0x/k/sG+K6G6UTHK1xei7g9rkMVzO2SZpDw1RQoCnfpEI4H3azvhr8lu5RxAGbib2rX59zSix4YltmAYSYYI4eHFNoNec4QaErRkGe8bRbNGr3LF8iHWrijR5XE9jMm5ykkJN0p6Ca8f49X/YRnlA78QnHVgryN71I4drxSsfNlf6YhQqbLlGag0YWfnQW8C7/IRYNiIL/GqrCwJQCS5j5L2f6FAJeFJ6ISEx70HDrXAecckqorbLYyNcglN1yYxF8k0ZuQwM0zZKHIDpZIG18T2GXFJ23+P/A9PAeXEV9J94OO7eLaHeotX5KK2HbsVENFewp+8hwsLskAlQWu5DggMZErnHrMyUZnU7SV4YDzhJ14HtClbSl11mVi5OuaSwGHsFV9yeXy+D1leii5Tnxs8SinMT5Jkt7XrbOJgAZwTEOmgHhM9FGRJItYqq37FYtygAteCtqB9uEjt7qsgRlkiKwxxt4pL0qI9fo46AmT/UI6Yvai9xnXUUCocfrGx0Lk2Qh5hPjW/2ZwSeyrcxaBpm0=
    - secure: DarDapxHcxWOP52OmXUtcj7vMM/YmYXOCa9dfjYy8hvuTWmcIvHByd1TjGF4MyM6WH6EZJCcgLHI4mmtjXPUMWqW6Q8aahDGWclEjbnGJMQ8bLO7nBwITbV+wIieezDYNGA+VWfGsWNgXObFose/Y0PWq9BPoBAlSQv+sld/4aFPDarGKfOaLHn3AHhvj2ajgNNZJeV47TIlIJIfDJveNxj5RlaMPFiuSoUscepA9rmAn95YxogfHZauzk69suWHI8/pnuVF7GO9Ah2sxSV+5Q/VFAB+jJklvPHhxdso+hdhqOJ8MXDbTADg9oFgg+QyzRCMktFfP2kaOXEwzBh6CcqPtZdQ7aoZ0awUetyfSAHb6dJNw3JbXVtL9qDhZEHz7f2XpQ3yM0dDVeARpRHF+gdmuLRBNv9+IXm2rZ09gBWoSlfoe/8TxdAXw0D+dmQUBDmqYUoV4ZfvK1TYOHPq0U1jxj5kb6uKqGRlMDlypn/AT5rkTR/l6uJEsyHyjuYN4DnOWSmPz+1NiK3A0V5Q7zG4h8nJdxQR7YzXRAtkrjv8N6ePHckjiBKaUMRHeXnye3QuApsJR5e/N69n+3FQGlOPQhpNFfrjOCt/h1NYcoxF09//n3r6Lx3Ix7R4ncI40IzDV6mI8xHWtzKk/woINNEUpadME9+kdDZ0KTiOXgo=

services:
  - docker

install:
  # Build both docker images (sdk and runtime)
  - docker build --target builder -t neo-sharp_sdk ./containers/
  - docker build --target runtime -t neo-sharp_runtime ./containers/

script:
  - dotnet restore
  - find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - docker run -p 8000:8000 -p 10332:10332 -d --rm --name neo-sharp-node neo-sharp_runtime
  - bash -c "sleep 10;if [ $(docker inspect -f '{{.State.Running}}' neo-sharp-node) = 'true' ]; then exit 0; else echo 'neo-sharp Node is not starting inside the clean runtime container!!' && exit 1; fi"

after_success:
  # After all tests OK, Send CodeDov report
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - bash <(curl -s https://codecov.io/bash) -v

before_deploy:
  # To deploy the docker images, first do login and tag
  - bash -c "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag neo-sharp_sdk cityofzion/neo-sharp:sdk_$TAG
  - docker tag neo-sharp_runtime cityofzion/neo-sharp:$TAG

deploy:
  # Push images to official docker repository
  - provider: script
    script: bash -c "docker push cityofzion/neo-sharp"
    on:
      repo: CityOfZion/neo-sharp
