sudo: required

services:
  - docker

env:
  - REPO=cryptotuga/neo-sharp

before_install:
  - docker --version

install:
  - docker build --target builder -t $REPO:SDK ./containers/

script:
  - docker run -p 8000:8000 -it --rm --name neo-sharp-SDK $REPO:SDK bash -c "cd /repo/neo-sharp && find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild && dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover && /bin/bash <(curl -s https://codecov.io/bash) -v"

after_success:
  - docker build -t $REPO:latest ./containers/

deploy:
  - provider: script
    script: bash "docker login -u $DOCKER_USER -p $DOCKER_PASS"
  
  - provider: script
    script: bash "docker push $REPO:SDK"

  - provider: script
    script: bash "docker push $REPO"
