language: csharp
os:
- linux
dist: trusty
dotnet: 2.1.300
mono: none
sudo: required
services:
- docker
before_install:
- docker build -t cryptotuga/neo-sharp:latest ./containers/
script:
- dotnet restore
- find test -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
- bash <(curl -s https://codecov.io/bash) -v
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=cryptotuga/neo-sharp
- docker push $REPO
env:
  global:
  - secure: C7zJQroPG709QDaUoyC2jzwepSpm+j0MohMx9pRPeZLmvYYPXLRK9nL6VFi+hdVRqsXLHxin3CLFv/lMKuyQXD7mmlzap2gZTi/mZf85cd45hvqgUA1wgqD+Lct7HBLDHQ8icUkirFTSamVeoO0sGE0VI8ck5A4y4ddzCxbhIBhPhsgs+EhHwE5ITMXG8MBVH+IM3Mq5sAqQKXYwXHMYi7rPZIKghB8HANgXOcEgeB4Z4XkGngkVNzABpLbtYjAI8xDTLGqcu6QSH8ENsOa7g7VD+JytHmeb4YOPBV/hOw85Kt6dOuHnNlQTRVn3ewKqgzj5xzoea9a8b+RLPlcUUpxK5UxaC/qqGhO3WL2Cjf2KZ20WSKcrIbDQGSZak4Wf2DPZt3M12mfMr5uCMoIwMk3xU417pAxXzRVhr4jC15rhaYj8Tfp9ds0vDBrLK5XK3T/T9rUJoAbEf6hSWiq7/ZMDI+JTWNHgwlNE/Gp7gziciN/BRdrr8WxJ/v3OfM0YSmeodxp/CzuYJQYEjCiE8YNwd8opORQeow8TYg2iOoS2bLlp0NUbDJ8f2QkQSPRYgtgUURdAtTmTeVghRiOEwSSKJovZw8ujX8kb4YVRMWqhGh1+MroqHYfQxR2MolFQXW6Hx/jDRXSW9022Zld/aocgFeMhor5hpOtAH64Fp7Y=
  - secure: UjeiDYvKGKwUgRiba5KVVixnXeToKoEZSVfH6a0k778UFQmm+jM4QyAmH9KkG+EhAcopzE8NK556NxwGILRrM/TFmwb0XqITMaCoT7AbRaT3AghTcDwZeB96ECw26LTCAjjCGpcJFK9I9j+uA8+BmD2GG+F0pBdgc75kIQyjjEgaBC509VysNPMjEf2RFRC+oG0WqFuxsAgxbVf3M/Fk8MBcjuDu7wjSqtEhEsxIBj5hUQjzycjoErn4s92NcHeZ6gWRdeVXKEoZU7HxnxU280Z9SfRHmgGF/Q7fvmWcUKQZxpGwqjpyP5Rqd6qAW53e3aV6cx2QvsPZ0MQZ4D+gB6RS73hASdJfhhcdQ5FuWytR0WvAG6jap4oV+1NoEVBvlabTcYq9wJeGsMAI+JPMRxm5MQcyddk7N4oEgGtqkYAfHJcd+IrKrsKqJBj+M6gNax/FzIwTqk5lU1/y2U+bjIKyeVU+7yqqZiWt8lxvgklxkJ7rsQ6YYqLq7Sq9KZIqH/TQaJ4IMKXx+LRFpRIvdXo7MPl2x8IBXyRiVFN95T5oA6DwfR2zjaVkyQqAT2vdOBvATSsCUfvBnB9B1d5iUhmmHDNLiJGXHi5ZjoT2G9AEiKbk8aJBaxwlcimOPrretiqDhg4fd6eh63bdImjAdLsaUcqc+OICVtrLap/HiHo=
